builds:
  - binary: lv
    id: lv
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    main: ./cmd/lv
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'   
