---
name: Release Drafter

on:
  push:
    branches:
      - master
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        with:
           # To not update the draft with unmerged PRs
           #   https://github.com/release-drafter/release-drafter/issues/917#issuecomment-907906352
           disable-releaser: ${{ github.ref_name != github.event.repository.default_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}